save_dir: workspace/nanodet_efficientnet
model:
  arch:
    name: GFL
    backbone:
      name: EfficientNetLite
      model_name: efficientnet_lite0
      out_stages: [2,4,6]
      activation: LeakyReLU
    fpn:
      name: PAN
      in_channels: [40, 112, 320]
      out_channels: 96
      start_level: 0
      num_outs: 3
    head:
      name: NanoDetHead
......
note: if out_stages was varied, in_channels was also need to change.
