#Config File example, model size 1.64M
#The shape of the head changes little, detection and tracking stability.
save_dir: workspace/nanodet_head_simple_320
model:
  arch:
    name: GFL
    backbone:
      name: ShuffleNetV2
      model_size: 0.5x
      out_stages: [2,3,4]
      activation: LeakyReLU
    fpn:
      name: PAN
      in_channels: [48, 96, 192]
      out_channels: 48
      start_level: 0
      num_outs: 3
    head:
      name: NanoDetHead
      num_classes: 1
      input_channel: 48
      feat_channels: 48
      stacked_convs: 2
      share_cls_reg: True
      octave_base_scale: 5
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0

class_names: ['head']
